# Generated by Django 4.1 on 2022-08-28 12:17

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', ckeditor_uploader.fields.RichTextUploadingField()),
                ('price', models.CharField(max_length=150)),
            ],
        ),
    ]
