# Generated by Django 4.0.7 on 2022-09-04 13:14

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=1000000)),
                ('image', models.ImageField(null=True, upload_to=core.models.courseImageUpload)),
                ('price', models.IntegerField()),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testemonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000000)),
                ('image', models.ImageField(null=True, upload_to=core.models.testemonialsImageUpload)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000000, null=True), size=None)),
                ('image', models.ImageField(null=True, upload_to=core.models.trainersImageUpload)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('description', models.CharField(max_length=1000000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_criteria_list', to='core.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EndContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('description', models.CharField(max_length=1000000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_content_list', to='core.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='testemonials',
            field=models.ManyToManyField(related_name='testemonials', to='core.testemonial'),
        ),
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(related_name='trainers', to='core.trainer'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('description', models.CharField(max_length=1000000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_list', to='core.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
