# Generated by Django 4.0.7 on 2022-09-04 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1000000, null=True), size=None),
        ),
    ]
