# Generated by Django 4.1.1 on 2022-09-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='courses',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
