# Generated by Django 4.1 on 2022-08-28 12:31

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_content_courses_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_content', ckeditor.fields.RichTextField()),
                ('image', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Testemonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='criterion',
            field=models.ManyToManyField(related_name='criteria', to='core.usercriteria'),
        ),
        migrations.AddField(
            model_name='courses',
            name='end_content',
            field=models.ManyToManyField(related_name='end_contents', to='core.endcontent'),
        ),
        migrations.AddField(
            model_name='courses',
            name='testemonial',
            field=models.ManyToManyField(related_name='testemonial', to='core.testemonials'),
        ),
        migrations.AddField(
            model_name='courses',
            name='trainer',
            field=models.ManyToManyField(related_name='trainers', to='core.trainers'),
        ),
    ]
