# Generated by Django 4.0.7 on 2022-09-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trainer_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndContent',
            new_name='CourseBenefit',
        ),
    ]
