# Generated by Django 4.1 on 2022-08-28 12:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_endcontent_testemonials_trainers_usercriteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemonials',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
