# Generated by Django 4.1 on 2022-08-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_testemonials_image_alter_trainers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='content',
            field=models.ManyToManyField(to='core.content'),
        ),
    ]
