# Generated by Django 4.1 on 2022-08-29 08:40

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_courses_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='trainer',
            new_name='trainers',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='testemonial',
        ),
        migrations.AddField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='criteria',
            field=ckeditor.fields.RichTextField(default='None'),
        ),
        migrations.AddField(
            model_name='courses',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='testemonials',
            field=models.ManyToManyField(related_name='testemonials', to='core.testemonials'),
        ),
        migrations.AddField(
            model_name='courses',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='testemonials',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='testemonials',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='testemonials',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testemonials',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='trainers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='trainers',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='trainers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainers',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.RemoveField(
            model_name='courses',
            name='content',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='end_content',
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='EndContent',
        ),
        migrations.DeleteModel(
            name='UserCriteria',
        ),
        migrations.AddField(
            model_name='courses',
            name='content',
            field=ckeditor.fields.RichTextField(default='None'),
        ),
        migrations.AddField(
            model_name='courses',
            name='end_content',
            field=ckeditor.fields.RichTextField(default='None'),
        ),
    ]
